/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE companyBaseService PLEASE EDIT ../company.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Company } from '../../domain/test_db/company';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Company.service.ts
 */

/*
 * SCHEMA DB Company
 *
	{
		Industry: {
			type: 'String'
		},
		Name: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Contact: {
			type: Schema.ObjectId,
			ref : "Company"
		},
	}
 *
 */
@Injectable()
export class CompanyBaseService {

    contextUrl: string = environment.endpoint + '/company';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * CompanyService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Company): Observable<Company> {
        return this.http
            .post<Company>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * CompanyService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * CompanyService.findByContact
    *   @description CRUD ACTION findByContact
    *   @param Objectid key Id of model to search for
    *
    */
    findByContact(id: string): Observable<Company[]> {
        return this.http
            .get<Company[]>(this.contextUrl + '/findByContact/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * CompanyService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Company> {
        return this.http
            .get<Company>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * CompanyService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Company[]> {
        return this.http
            .get<Company[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * CompanyService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Company): Observable<Company> {
        return this.http
            .post<Company>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
