/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE personBaseService PLEASE EDIT ../person.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Person } from '../../domain/test_db/person';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Person.service.ts
 */

/*
 * SCHEMA DB Person
 *
	{
		Birthday: {
			type: 'Date'
		},
		Name: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Contact: {
			type: Schema.ObjectId,
			ref : "Company"
		},
	}
 *
 */
@Injectable()
export class PersonBaseService {

    contextUrl: string = environment.endpoint + '/contact';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * PersonService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Person): Observable<Person> {
        return this.http
            .post<Person>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * PersonService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * PersonService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Person> {
        return this.http
            .get<Person>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * PersonService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Person[]> {
        return this.http
            .get<Person[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * PersonService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Person): Observable<Person> {
        return this.http
            .post<Person>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
